---
- hosts: all
  become: true
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
      autoremove: yes

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist