---
  - name: Update and upgrade apt packages
    ansible.builtin.apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    ansible.builtin.apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    ansible.builtin.apt:
      autoremove: yes

  - name: Upgrade the OS (apt-get dist-upgrade)
    apt:
      upgrade: dist
  
  - name: Enable unattended-upgrades
    apt:
      name: "unattended-upgrades"
      state: latest

  - name: install apt useful packages
    apt:
      name: "{{ apt_default_apps }}"
      state: latest